apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: frontend
  namespace: devopscafe
spec:
  selector:
    matchLabels:
      app: ravi-learning
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: ravi-learning
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: registry.hub.docker.com/devopscafe/ravi-comments:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
